### PR TITLE
Add open telemetry fields to messages by default if present

### PR DESCRIPTION
**Pull request by bliof-fc**
Support open-telemetry and add trace_id and span_id to logs events.

### CODE REVIEW

**Comment by colin-humphrey** [comment]
@bliof-fc please can you confirm when this will be actioned and/or whether any changes need to happen given the aging of this PR?

**Comment by bliof-fc** [comment]
@colin-humphrey I'll try to update till the end of the week, but feel free to edit the PR at will. It just needs a rebase and few specs

**Comment by fc-infosec-sast** [comment]
<h2>✅ SAST Report</h2>

No issues found. Good job! 💪

**Comment by jamesrwhite** [comment]
@bliof-fc I've added one basic test, was there any other cases you wanted to cover?

**Comment by bliof-fc** [comment]
@jamesrwhite LGTM 👍 

It seems there is always span / context regardless if it is valid or invalid

https://github.com/open-telemetry/opentelemetry-ruby/blob/d365dfeb3982f09cd62a17c6e67eb3792f56e460/api/lib/opentelemetry/trace.rb#L48-L51
https://github.com/open-telemetry/opentelemetry-ruby/blob/d365dfeb3982f09cd62a17c6e67eb3792f56e460/api/lib/opentelemetry/trace/span_context.rb

**Review by jamesrwhite — APPROVED** [review]

**Pull request merged**
